import Head from "next/head";
import Image from "next/image";
import { AiFillLinkedin, AiFillGithub, SiIndeed } from "react-icons/ai";
import useState from "react";
export default function Home() {
  function goToWeb(link) {
    window.open(link);
  }
  // const [darkMode, setDarkMode] = useState(false);
  const Linkedin = "https://www.linkedin.com/in/anthony-silva-3424a4253/";
  const GitHub = "https://github.com/anthonysilva98/";
  const Resume = "Anthony_Silva_Website_Resume.pdf";
  return (
    <div>
      <link
        href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
        rel="stylesheet"
      ></link>
      <Head>
        <title>Anthony Silva Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="style.css" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <ul className="flex items-center">
              <li></li>
              <li>
                <a
                  className="bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                  onClick={() => {
                    window.open(Resume);
                  }}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 font-medium text-teal-600 md:text-6xl">
              Anthony Silva
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl"> Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Full Stack Software Developer with a focus on mobile and web
              development. 5 years of experience developing mobile apps, with 2
              years of professional experience building out websites and mobile
              application for Project Centerline.
            </p>
          </div>
          {/* <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <button onClick={() => goToWeb(Linkedin)}>
              <AiFillLinkedin />
            </button>
            <button onClick={() => goToWeb(GitHub)}>
              <AiFillGithub />
            </button>
          </div> */}
        </section>
        <section>
          <h3 className="text-3xl py-10 justify-center flex  text-gray-600">
            Tech Stack
          </h3>
          <section>
            <div className="pt-10 flex-wrap lg:flex gap-10 justify-center grid ">
              <div className="flex justify-start align-middle py-5 ">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-30 pl-12 "
                    src="ReactNativelogo.jfif"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  React Native
                </p>
              </div>
              <div className="flex justify-start align-middle py-5 ">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-30 pl-12 "
                    src="ReactNativelogo.jfif"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  React
                </p>
              </div>
              <div className="flex justify-start align-middle py-5 ">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-30 pl-12 "
                    src="GQL.png"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  GraphQL
                </p>
              </div>
              <div className="flex justify-start self-auto py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="JSLogo.png"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  JavaScript
                </p>
              </div>

              <div className="flex justify-start align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="TSLogo.png"
                  />
                </picture>
                <p className="list-none text-2xl align-middle pl-5 justify-center py-5  text-gray-600">
                  TypeScript
                </p>
              </div>
              <div className="flex justify-start align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="FirebaseLogo.jfif"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  Firebase
                </p>
              </div>
              <div className="flex justify-start align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="ExpoLogo.png"
                  />
                </picture>
                <li className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  Expo
                </li>
              </div>
            </div>
            <div>
              <h3 className="text-3xl pt-20 justify-center flex text-gray-600">
                React-Native Projects Portfolio
              </h3>
            </div>
          </section>
          <div className="lg:flex gap-10 justify-center grid ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center min-w-700">
              <p className="text-2xl py-1 text-gray-800 flex-1">
                UPS Tracker Demo
              </p>
              <video playsInline autoPlay loop muted className="h-300">
                <source src="upsDemo.mp4" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-black-800">GraphQL</p>
              <p className="text-md py-1 text-gray-800">
                This project uses a custom GraphQL backend that allows for
                filtering, searching and viewing of items that are stored in a
                firebase database.
              </p>
              <p className="text-2xl py-1 text-black-800">TailwindCSS</p>
              <p className="text-md py-1 text-gray-800">
                This project leverages TailwindCSS to allow inline styling of
                components, and help familiarize common design practices and
                syntax.
              </p>
              <p className="text-2xl py-1 text-black-800">FireBase</p>
              <p className="text-md py-1 text-gray-800">
                This project uses Firebase to store our data in the backend, and
                allows us to make requests to make GQL requests to grab specific
                data that pertains to individuals.
              </p>
            </div>
            <div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <p className="text-2xl py-1 text-black-800 flex-1">
                  UberEats App Demo
                </p>
                <video playsInline autoPlay loop muted className="h-300">
                  <source src="UberEats.mp4" type="video/mp4" />
                </video>
                <p className="text-2xl py-1 text-black-800">
                  Google Places Api
                </p>
                <p className="text-md py-1 text-gray-800">
                  This project leverages the Google Places API to allow users to
                  search for restaurants and places that they would like to
                  order from.
                </p>
                <p className="text-2xl py-1 text-black-800">FireBase</p>
                <p className="text-md py-1 text-gray-800">
                  This project uses Firebase Firestore as our backend to this
                  project. This handled orders that were created by users and
                  allowed for an easy out of the box solution to store our
                  information.
                  {/* Using Firebase Firestore, was able to allow users to create an
                  order which would be sent to Firestore to be retreived when
                  showing their final order. Firebase backend that handles
                  orders that are sent out through the app */}
                </p>
                <p className="text-2xl py-1 text-black-800">Yelp Api</p>
                <p className="text-md py-1 text-gray-800">
                  This project uses the Yelp API to display real restaurant data
                  that we get from our Google Places API.
                </p>
                <p className="text-2xl py-1 text-black-800">Redux</p>
                <p className="text-md py-1 text-gray-800">
                  Redux was used in this project and allowed for global state
                  management when dealing with creating orders
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-2xl py-1 text-black-800">Step Counter App</p>
              <video playsInline autoPlay loop muted className="h-300">
                <source src="StepCounterApp.mov" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-black-800 flex-1">
                Apple HealthKit
              </p>
              <p className="text-md py-1 text-gray-800">
                This project uses Apple Healthkit to interface with existing
                native modules from the health app, and render them using react
                native components.
              </p>
              <p></p>
              <p className="text-2xl py-1 text-black-800">
                React Native Reanimated
              </p>
              <p className="text-md py-1 text-gray-800">
                React Native Reanimated is used in this project to display
                animated graphics, like the circle rendering based off of a
                daily step goal.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10 justify-center grid">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center">
              <p className="text-2xl py-1 text-black-800">
                Uber Rideshare Demo
              </p>
              <video playsInline autoPlay loop muted className="h-300">
                <source src="UberDemo.mov" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-black-800">Google Places API</p>
              <p className="text-md py-1 text-gray-800">
                Google Places API used for getting places and autofilling for
                better user experience
              </p>
              <p className="text-2xl py-1 text-black-800">TailwindCSS</p>
              <p className="text-md py-1 text-gray-800">
                Allows for easy and fast paced components to be built
              </p>
              <p className="text-2xl py-1 text-black-800">
                Google Distance Matrix
              </p>
              <p className="text-md py-1 text-gray-800">
                Google Distance matrix allows for calculating how long a ride
                will take along with how much that ride should cost
              </p>
              <p className="text-2xl py-1 text-black-800">Redux</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management and allows for users to request rides
                and set destinations start points
              </p>
            </div>
            <div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <p className="text-2xl py-1 text-black-800">Nike App Demo</p>
                <video playsInline autoPlay loop muted className="h-300">
                  <source src="NikeAPP.mov" type="video/mp4" />
                </video>
                <p className="text-2xl py-1 text-black-800">Redux</p>
                <p className="text-md py-1 text-gray-800">
                  Used for state management accross the app and allows user to
                  build cart before placeing their order
                </p>
                <p className="text-2xl py-1 text-black-800">
                  Custom Restful Api
                </p>
                <p className="text-md py-1 text-gray-800">
                  Custom Restful API that uses Node.js and Express to make
                  requests to our backend.
                </p>
                <p className="text-2xl py-1 text-black-800">MongoDB</p>
                <p className="text-md py-1 text-gray-800">
                  MongoDB database was used in this project as our database and
                  allows users orders to be saved and retreived.
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-2xl py-1 text-black-800">Twitter Clone</p>
              <video playsInline autoPlay loop muted className="h-300">
                <source src="TwitterClone.mp4" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-black-800">Express</p>
              <p className="text-md py-1 text-gray-800">
                Express was used in this project to allow for custom APIs to our
                backend.
              </p>
              <p className="text-2xl py-1 text-black-800">Prisma</p>
              <p className="text-md py-1 text-gray-800">
                Prisma was used in this project as our database used for storing
                users, tweets, and other information related to tweets.
              </p>
              <p className="text-2xl py-1 text-black-800">Node</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management accross the app and allows user to
                build cart before placeing their order.
              </p>
              <p className="text-2xl py-1 text-black-800">AWS SMS</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management accross the app and allows user to
                build cart before placeing their order.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
